services:
  - type: web
    name: taskmanager-backend
    env: java
    buildCommand: "./gradlew build --no-daemon"
    startCommand: "java -jar build/libs/taskmanager-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
